export { Api } from "./tl";
import * as tl from "./tl";
export { TelegramClient } from "./client/TelegramClient";
export { Connection } from "./network";
export { version } from "./Version";
export { Logger } from "./extensions/Logger";
import * as utils from "./Utils";
import * as errors from "./errors";
import * as sessions from "./sessions";
import * as extensions from "./extensions";
import * as helpers from "./Helpers";
import * as client from "./client";
import * as password from "./Password";
import * as events from "./events";
export { utils, errors, sessions, extensions, helpers, tl, password, client, events };

import { Api } from "./tl";
import { TelegramClient } from "./client/TelegramClient";
declare const telegram: {
  Api: typeof Api;
  TelegramClient: typeof TelegramClient;
  sessions: typeof sessions;
  events: typeof events;
  errors: typeof errors;
  extensions: typeof extensions;
  utils: typeof utils;
  helpers: typeof helpers;
  tl: typeof tl;
  client: typeof client;
  password: typeof password;
};
export default telegram;
